### ISSUE TITLE
can this run cloudflare check browser code?

### ISSUE THREAD

**Issue by luanon404** [ffeelix/jsvm#1]
the last post of cloudflare has js code that you must run it to get data of browser, can your code do this? i used jsdom to run but its not work

**Comment by ffeelix** [comment]
Hi,

I currently don't have the cloudflare code to fetch the challenge js, however this js script can be found on any cloudflare managed site with the bot management option on.

**Comment by luanon404** [comment]
> Hi,
> 
> I currently don't have the cloudflare code to fetch the challenge js, however this js script can be found on any cloudflare managed site with the bot management option on.

sorry i mean can i run your code using nodejs?

**Comment by ffeelix** [comment]
If you're talking about the cloudflare deobfuscator yeah it should be able to run in node js

**Comment by luanon404** [comment]
> If you're talking about the cloudflare deobfuscator yeah it should be able to run in node js

thanks for your reply and sorry for my stupid question

**Comment by luanon404** [comment]
you can delete this issue
